---
- hosts: server1

  tasks:
   - name: Nginx setup
     yum: pkg=nginx state=installed update_cache=true

   - name: Start Nginx 
     service: name=nginx state=started

   - name: index.html copy
     template: src=index.html.j2 dest=/home/ubuntu/index.html
